[package]
name = "fescent"
version = "0.1.0"
edition = "2021"

[lib]
name = "fescent"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.25.0", features = ["extension-module"] }
numpy = "0.25.0"
rand = "0.9.1"